// Icônes Material Design (mêmes noms que l'app mobile : @expo/vector-icons MaterialCommunityIcons)
import {
    mdiBriefcaseOutline,
    mdiGamepadVariantOutline,
    mdiTools,
    mdiPlayCircleOutline,
    mdiSchoolOutline,
    mdiCodeBraces,
    mdiMusicNote,
    mdiCameraOutline,
    mdiImageOutline,
    mdiVideoOutline,
    mdiBookOpenVariant,
    mdiChatOutline,
    mdiEmailOutline,
    mdiCalendarMonthOutline,
    mdiCartOutline,
    mdiHeartPulse,
    mdiDumbbell,
    mdiMapMarkerOutline,
    mdiAirplane,
    mdiCarOutline,
    mdiFoodAppleOutline,
    mdiFinance,
    mdiBankOutline,
    mdiShieldLockOutline,
    mdiCloudOutline,
    mdiCogOutline,
    mdiPaletteOutline,
    mdiPuzzleOutline,
    mdiAccountGroupOutline,
    mdiNewspaperVariantOutline,
    mdiWeatherPartlyCloudy,
    mdiFlaskOutline,
    mdiRocketLaunchOutline,
    mdiStarOutline,
    mdiShapeOutline,
    mdiEarth,
    mdiAndroid,
    mdiMicrosoftWindows,
    mdiApple,
    mdiLinux,
    mdiDownload,
    mdiHeart,
    mdiShieldCheck,
    mdiShieldAlert,
} from "@mdi/js";

export const ICONS = {
    "briefcase-outline": mdiBriefcaseOutline,
    "gamepad-variant-outline": mdiGamepadVariantOutline,
    "tools": mdiTools,
    "play-circle-outline": mdiPlayCircleOutline,
    "school-outline": mdiSchoolOutline,
    "code-braces": mdiCodeBraces,
    "music-note": mdiMusicNote,
    "camera-outline": mdiCameraOutline,
    "image-outline": mdiImageOutline,
    "video-outline": mdiVideoOutline,
    "book-open-variant": mdiBookOpenVariant,
    "chat-outline": mdiChatOutline,
    "email-outline": mdiEmailOutline,
    "calendar-month-outline": mdiCalendarMonthOutline,
    "cart-outline": mdiCartOutline,
    "heart-pulse": mdiHeartPulse,
    "dumbbell": mdiDumbbell,
    "map-marker-outline": mdiMapMarkerOutline,
    "airplane": mdiAirplane,
    "car-outline": mdiCarOutline,
    "food-apple-outline": mdiFoodAppleOutline,
    "finance": mdiFinance,
    "bank-outline": mdiBankOutline,
    "shield-lock-outline": mdiShieldLockOutline,
    "cloud-outline": mdiCloudOutline,
    "cog-outline": mdiCogOutline,
    "palette-outline": mdiPaletteOutline,
    "puzzle-outline": mdiPuzzleOutline,
    "account-group-outline": mdiAccountGroupOutline,
    "newspaper-variant-outline": mdiNewspaperVariantOutline,
    "weather-partly-cloudy": mdiWeatherPartlyCloudy,
    "flask-outline": mdiFlaskOutline,
    "rocket-launch-outline": mdiRocketLaunchOutline,
    "star-outline": mdiStarOutline,
    "shape-outline": mdiShapeOutline,
    "earth": mdiEarth,
    "android": mdiAndroid,
    "microsoft-windows": mdiMicrosoftWindows,
    "apple": mdiApple,
    "linux": mdiLinux,
    "download": mdiDownload,
    "heart": mdiHeart,
    "shield-check": mdiShieldCheck,
    "shield-alert": mdiShieldAlert,
};

// Icônes proposées pour les catégories
export const CATEGORY_ICONS = [
    "briefcase-outline",
    "gamepad-variant-outline",
    "tools",
    "play-circle-outline",
    "school-outline",
    "code-braces",
    "music-note",
    "camera-outline",
    "image-outline",
    "video-outline",
    "book-open-variant",
    "chat-outline",
    "email-outline",
    "calendar-month-outline",
    "cart-outline",
    "heart-pulse",
    "dumbbell",
    "map-marker-outline",
    "airplane",
    "car-outline",
    "food-apple-outline",
    "finance",
    "bank-outline",
    "shield-lock-outline",
    "cloud-outline",
    "cog-outline",
    "palette-outline",
    "puzzle-outline",
    "account-group-outline",
    "newspaper-variant-outline",
    "weather-partly-cloudy",
    "flask-outline",
    "rocket-launch-outline",
    "star-outline",
    "shape-outline",
    "earth"
];
